# Site settings
title: Brightspace UI
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Brightspace UI
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://ui.valence.d2l.com" # the base hostname & protocol for your site
exclude: [bower_components, node_modules, vendor, bower.json, Gemfile, package.json, README.md]
highlighter: pygments
defaults:
  -
    values:
      layout: "page"
collections:
  components:
    output: true
  personas:
    output: true
sass:
  style: :compressed
gems: ['jekyll/minibundle']
minibundle:
  minifier_commands:
    js: node_modules/.bin/uglifyjs -
