name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - uses: Brightspace/third-party-actions@actions/cache
        id: cache
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint (JavaScript)
        run: npm run lint:eslint
      - name: Lint (CSS)
        run: npm run lint:style
      - name: Lint (Lit)
        run: npm run lint:lit
      - name: Unit Tests
        run: npm run test:unit
      - name: Build
        run: npm run build:prod
      - name: Assume role
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::037018655140:role/daylight.d2l.dev-githubactions-access
          role-duration-seconds: 3600
          aws-region: ca-central-1
      - name: Deploy - branch
        run: aws s3 sync --delete ./_site/ "s3://daylight.d2l.dev/branches/pr-${{ github.event.number }}"
        env:
          # cred variables set in the "Assume role" step
          AWS_DEFAULT_REGION: ca-central-1
      - uses: Brightspace/third-party-actions@actions/github-script
        with:
          script: |
            const url = `https://pr-${context.issue.number}-daylight.d2l.dev`
            await github.checks.create({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: "${{ github.event.pull_request.head.sha }}",
              name: 'Preview URL',
              status: 'completed',
              conclusion: 'neutral',
              output: { title: url, summary: `Preview your changes at: ${url}`}
            })
