name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - uses: Brightspace/third-party-actions@actions/cache
        id: cache
        with:
          path: '**/node_modules'
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install AWS dependencies
        run: npm i aws-sdk --no-save
      - name: Build
        run: npm run build:prod
      - name: Assume role
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::037018655140:role/daylight.d2l.dev-githubactions-access
          role-duration-seconds: 3600
          aws-region: ca-central-1
      - name: Deploy - master
        run: aws s3 sync --delete ./_site/ s3://daylight.d2l.dev/branches/master
        env:
          # cred variables set in the "Assume role" step
          AWS_DEFAULT_REGION: ca-central-1
      - name: Deploy - commit
        run: aws s3 sync --delete ./_site/ "s3://daylight.d2l.dev/commits/${GITHUB_SHA}"
        env:
          # cred variables set in the "Assume role" step
          AWS_DEFAULT_REGION: ca-central-1
