name: Visual Diff
on: pull_request
jobs:
  build:
    name: Visual Diff
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Assume role
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: arn:aws:iam::037018655140:role/visual-diff-githubactions-access
          role-duration-seconds: 3600
          aws-region: ca-central-1
      - name: Visual Diff Tests
        uses: BrightspaceUI/actions/visual-diff@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
